language: python
matrix:
  include:
    - { python: 2.7, dist: xenial, env: TOXENV=py27 }
    - { python: 3.7, dist: xenial, env: TOXENV=py37 }
cache:
  pip: true
  apt: true
addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-4'
    packages:
    - libgnutls28-dev
    - libjpeg-progs
    - libimage-exiftool-perl
    - gifsicle
    - python-all-dev
    - scons
    - libboost-python-dev
    - libexiv2-dev
    - ffmpeg
install:
  - pip install tox codecov
script:
  - tox
affter_success:
  - codecov
